# Generated by Django 5.2.8 on 2025-12-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleFieldPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("title", "Título"),
                            ("description", "Descripción"),
                            ("price", "Precio"),
                            ("currency", "Moneda"),
                            ("maintenance_fee", "Cuota de Mantenimiento"),
                            ("property_type", "Tipo de Propiedad"),
                            ("property_subtype", "Subtipo de Propiedad"),
                            ("status", "Estado"),
                            ("bedrooms", "Dormitorios"),
                            ("bathrooms", "Baños"),
                            ("half_bathrooms", "Medios Baños"),
                            ("garage_spaces", "Espacios de Garaje"),
                            ("garage_type", "Tipo de Garaje"),
                            ("land_area", "Área de Terreno"),
                            ("built_area", "Área Construida"),
                            ("front_measure", "Medida del Frente"),
                            ("depth_measure", "Profundidad"),
                            ("coordinates", "Coordenadas"),
                            ("exact_address", "Dirección Exacta"),
                            ("real_address", "Dirección Real"),
                            ("department", "Departamento"),
                            ("province", "Provincia"),
                            ("district", "Distrito"),
                            ("urbanization", "Urbanización"),
                            ("water_service", "Servicio de Agua"),
                            ("energy_service", "Servicio de Energía"),
                            ("drainage_service", "Servicio de Drenaje"),
                            ("gas_service", "Servicio de Gas"),
                            ("amenities", "Servicios/Amenidades"),
                            ("zoning", "Zonificación"),
                            ("price_history", "Historial de Precios"),
                            ("images", "Imágenes"),
                            ("videos", "Videos"),
                            ("documents", "Documentos"),
                            ("financial_info", "Información Financiera"),
                            ("rooms", "Ambientes"),
                            ("owner_contact", "Contacto del Propietario"),
                            ("responsible", "Responsable"),
                            ("assigned_agent", "Agente Asignado"),
                        ],
                        help_text="Campo de la propiedad",
                        max_length=50,
                    ),
                ),
                (
                    "can_view",
                    models.BooleanField(
                        default=True, help_text="¿Puede ver este campo?"
                    ),
                ),
                (
                    "can_edit",
                    models.BooleanField(
                        default=False, help_text="¿Puede editar este campo?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_permissions",
                        to="users.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso de Campo por Rol",
                "verbose_name_plural": "Permisos de Campos por Roles",
                "db_table": "role_field_permissions",
                "unique_together": {("role", "field_name")},
            },
        ),
    ]
