# Generated by Django 5.2.8 on 2026-01-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rolefieldpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('green', 'Verde (predeterminado)'), ('black', 'Negro')], default='green', max_length=20),
        ),
    ]
