# Generated by Django 5.2.10 on 2026-02-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Area',
        ),

        migrations.RenameField(
            model_name='customuser',
            old_name='department',
            new_name='area',
        ),

        migrations.AddField(
            model_name='role',
            name='area',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='roles',
                to='users.area',
            ),
        ),
    ]
