"""
Django settings for janis_core3 project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths...
BASE_DIR = Path(__file__).resolve().parent.parent

# 1) Elegimos archivo env
ENV_FILE = os.environ.get("ENV_FILE", ".env.local")

# 2) Cargamos SOLO ese archivo y sobrescribimos (para que cambie al vuelo)
load_dotenv(dotenv_path=BASE_DIR / ENV_FILE, override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'clave_para_desarrollo')

# DEBUG desde variable de entorno (False por defecto en producción)
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes')

# Hosts permitidos desde App Setting `ALLOWED_HOSTS` (coma-separados)
# Añadir el host de ngrok utilizado en desarrollo para permitir peticiones externas
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,semipeaceful-highhandedly-tyisha.ngrok-free.dev').split(',') if h.strip()]
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users.apps.UsersConfig",
    'django.contrib.humanize',
    # Third-party apps
    "rest_framework",
    "corsheaders",
    "django_filters",
    "prueba",
    "properties.apps.PropertiesConfig",
    "security",
    "whatsapp",
    "chat",
    "tasks",
    "storages",
    "notifications",
]
# Activar token_blacklist solo si se pide por env (evita migración rota en SQL Server local)
if os.environ.get("ENABLE_TOKEN_BLACKLIST", "False").lower() in ("1", "true", "yes"):
    INSTALLED_APPS.append("rest_framework_simplejwt.token_blacklist")

# Facebook Pixel ID (opcional, para campañas)
import os
FACEBOOK_PIXEL_ID = os.environ.get('FACEBOOK_PIXEL_ID', '')
AUTH_USER_MODEL = 'users.CustomUser'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CORS middleware should be placed as high as possible
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]

ROOT_URLCONF = "janis_core3.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
                # Context processor para exponer `profile` en todas las plantillas
                "users.context_processors.user_profile",
                # Context processor para notificaciones de matching
                "properties.context_processors.match_notifications",
            ],
        },
    },
]

WSGI_APPLICATION = "janis_core3.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Normalizar DB user/host antes de definir el diccionario DATABASES
_db_user = os.environ.get('DB_USER', 'sqladmin') or 'sqladmin'
_db_host = os.environ.get('DB_HOST', 'janis-server.database.windows.net')
_server_short = _db_host.split('.')[0] if _db_host else _db_host

# Solo aplicar el formato user@server cuando sea Azure SQL (database.windows.net)
if _db_host and "database.windows.net" in _db_host.lower():
    if '@' not in _db_user and _server_short:
        _db_user = f"{_db_user}@{_server_short}"

_db_name = os.environ.get('DB_NAME')
if not _db_name:
    if DEBUG:
        _db_name = 'propify_local'
    else:
        raise RuntimeError("DB_NAME no definido en staging/prod.")

DATABASES = {
    'default': {
        # Leer credenciales desde variables de entorno para producción
        'ENGINE': os.environ.get('DB_ENGINE', 'mssql'),
        'NAME': _db_name,
        'USER': _db_user,
        'PASSWORD': os.environ.get('DB_PASS', os.environ.get('DB_PASSWORD', '')),
        'HOST': _db_host,
        'PORT': os.environ.get('DB_PORT', '1433'),
        'OPTIONS': {
            'driver': os.environ.get('DB_DRIVER', 'ODBC Driver 18 for SQL Server'),
            'extra_params': os.environ.get('DB_EXTRA_PARAMS', 
                'Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=60;MARS_Connection=no;ConnectRetryCount=3;ConnectRetryInterval=10;' 
                if 'database.windows.net' in _db_host 
                else 'Encrypt=no;TrustServerCertificate=yes;Connection Timeout=60;'
            ),
            'unicode_results': True, # Forzado para evitar SystemError en Azure App Service
        },
        'CONN_MAX_AGE': 0, # FORCE NO POOLING for Azure SQL to avoid IMC06/Broken Pipe errors on idle
        'TIME_ZONE': os.environ.get('DB_TIME_ZONE', 'America/Lima'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-pe"

TIME_ZONE = "America/Lima"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://localhost').split(',') if o.strip()
]
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Optional Azure Blob storage for media files.
# If AZURE_ACCOUNT_NAME and AZURE_ACCOUNT_KEY are provided in the environment,
# the project will use django-storages Azure backend so both local and remote
# deployments can share the same media container.
AZURE_ACCOUNT_NAME = os.environ.get('AZURE_ACCOUNT_NAME')
AZURE_ACCOUNT_KEY = os.environ.get('AZURE_ACCOUNT_KEY')
AZURE_CONTAINER = os.environ.get('AZURE_CONTAINER', 'media')

if AZURE_ACCOUNT_NAME and AZURE_ACCOUNT_KEY:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": AZURE_ACCOUNT_NAME,
                "account_key": AZURE_ACCOUNT_KEY,
                "azure_container": AZURE_CONTAINER,  # media
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/"
else:
    # fallback local (dev sin Azure)
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Optimización para desarrollo: No buscar archivos estáticos en cada carga si estamos en DEBUG
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', 'Qk9vQ2h2d2ZpQ2ZpQ2h2d2ZpQ2ZpQ2h2d2ZpQ2ZpQ2g=')
LOGIN_URL = '/users/login/'

# Django REST Framework basic add (customize as needed)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    # Throttling removed to allow unrestricted access per request
}

# SimpleJWT configuration: short-lived access tokens and rotating refresh tokens
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Production security recommendations (set these in production environment):
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 3600
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# CORS settings - allow the production web origin and localhost for development.
# For mobile native apps using Retrofit this is not strictly necessary, but
# android emulators or embedded webviews may require correct origins.
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:8000').split(',') if o.strip()
]

# If you prefer to allow all origins during development, set the following to True
# CORS_ALLOW_ALL_ORIGINS = True


# ============================================================================
# CONFIGURACIÓN WHATSAPP BUSINESS API
# ============================================================================
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID')
WHATSAPP_BUSINESS_ACCOUNT_ID = os.environ.get('WHATSAPP_BUSINESS_ACCOUNT_ID')
WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN')
WHATSAPP_VERIFY_TOKEN = os.environ.get('WHATSAPP_VERIFY_TOKEN')
WHATSAPP_API_VERSION = os.environ.get('WHATSAPP_API_VERSION', 'v18.0')
WHATSAPP_API_BASE_URL = f'https://graph.instagram.com/{WHATSAPP_API_VERSION}'

# Allow cookies/credentials if your API uses session authentication
CORS_ALLOW_CREDENTIALS = True

# OpenSearch configuration (hosts can be a comma-separated list in env var)
OPENSEARCH_HOSTS = [h.strip() for h in os.environ.get('OPENSEARCH_HOSTS', 'http://localhost:9200').split(',') if h.strip()]

# ============================================================================
# WHATSAPP DEFAULTS (production-safe overrides)
# If you want incoming messages without tracking to be assigned to a default
# property or social network, set these environment variables to the integer
# primary key of the corresponding DB record. Leave empty to keep current
# behavior (first()-based fallback).
WHATSAPP_DEFAULT_PROPERTY_ID = os.environ.get('WHATSAPP_DEFAULT_PROPERTY_ID') or None
WHATSAPP_DEFAULT_SOCIAL_ID = os.environ.get('WHATSAPP_DEFAULT_SOCIAL_ID') or None

LOGGING = {
   "version": 1,
   "disable_existing_loggers": False,
   "handlers": {"console": {"class": "logging.StreamHandler"}},
   "loggers": {
       "django.db.backends": {
           "handlers": ["console"],
           "level": "DEBUG",
       }
   }
}

WP_BASE_URL = os.getenv("WP_BASE_URL", "").rstrip("/")
WP_USER = os.getenv("WP_USER", "")
WP_APP_PASSWORD = os.getenv("WP_APP_PASSWORD", "")
WP_TIMEOUT = int(os.getenv("WP_TIMEOUT", "30"))
INTERNAL_SYNC_KEY = os.getenv("INTERNAL_SYNC_KEY", "")
