# Generated by Django 5.2.8 on 2026-01-09 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Renombrar el modelo a nivel de estado de migraciones sin crear una tabla nueva.
        migrations.RenameModel(
            old_name='Conversation',
            new_name='MailThread',
        ),
    ]
