# Generated by Django 5.2.8 on 2025-12-11 17:54

import django.db.models.deletion
import encrypted_model_fields.fields
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=5)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "currencies",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Distrito",
                "verbose_name_plural": "Distritos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "document_types",
            },
        ),
        migrations.CreateModel(
            name="DrainageServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tipo de Servicio de Drenaje",
                "verbose_name_plural": "Tipos de Servicio de Drenaje",
                "db_table": "drainage_service_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EnergyServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tipo de Servicio de Energía",
                "verbose_name_plural": "Tipos de Servicio de Energía",
                "db_table": "energy_service_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FloorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "floor_types",
            },
        ),
        migrations.CreateModel(
            name="GarageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "garage_types",
            },
        ),
        migrations.CreateModel(
            name="GasServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tipo de Servicio de Gas",
                "verbose_name_plural": "Tipos de Servicio de Gas",
                "db_table": "gas_service_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "image_types",
            },
        ),
        migrations.CreateModel(
            name="LevelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "level_types",
            },
        ),
        migrations.CreateModel(
            name="MeasurementUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "measurement_units",
            },
        ),
        migrations.CreateModel(
            name="NegotiationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de negociación",
                "verbose_name_plural": "Estados de negociación",
                "db_table": "negotiation_statuses",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "professions",
            },
        ),
        migrations.CreateModel(
            name="PropertyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "property_statuses",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PropertySubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "property_subtypes",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "property_types",
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "room_types",
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "service_types",
            },
        ),
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Clase de ícono FontAwesome opcional",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Red Social",
                "verbose_name_plural": "Redes Sociales",
                "db_table": "social_networks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="VideoType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "video_types",
            },
        ),
        migrations.CreateModel(
            name="WaterServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tipo de Servicio de Agua",
                "verbose_name_plural": "Tipos de Servicio de Agua",
                "db_table": "water_service_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_id",
                    models.CharField(
                        help_text="ID de WhatsApp Business (wa.me)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nombre o alias para mostrar", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Teléfono WhatsApp",
                "verbose_name_plural": "Teléfonos WhatsApp",
                "db_table": "whatsapp_phones",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, default="", max_length=20, unique=True
                    ),
                ),
                (
                    "codigo_unico_propiedad",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="Código Único Propiedad",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "antiquity_years",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Aplica únicamente para propiedades con estado de antigüedad",
                        null=True,
                        verbose_name="Años de antigüedad",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True,
                        help_text="Aplica únicamente para propiedades en construcción",
                        null=True,
                        verbose_name="Fecha estimada de entrega",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "maintenance_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("has_maintenance", models.BooleanField(default=False)),
                (
                    "floors",
                    models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                (
                    "bedrooms",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "bathrooms",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "half_bathrooms",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "garage_spaces",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "land_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "built_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "front_measure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "depth_measure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "real_address",
                    models.TextField(
                        blank=True,
                        help_text="Dirección exacta que aparece en documentos legales",
                        null=True,
                        verbose_name="Dirección Real (de documentos)",
                    ),
                ),
                (
                    "exact_address",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Dirección Exacta (para mapa)",
                    ),
                ),
                (
                    "coordinates",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "urbanization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("amenities", models.TextField(blank=True, null=True)),
                ("zoning", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_ready_for_sale", models.BooleanField(default=False)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "built_area_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="built_properties",
                        to="properties.measurementunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.currency",
                    ),
                ),
                (
                    "drainage_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drainage_properties",
                        to="properties.drainageservicetype",
                        verbose_name="Servicio de Drenaje",
                    ),
                ),
                (
                    "energy_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="energy_properties",
                        to="properties.energyservicetype",
                        verbose_name="Servicio de Energía",
                    ),
                ),
                (
                    "garage_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.garagetype",
                    ),
                ),
                (
                    "gas_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gas_properties",
                        to="properties.gasservicetype",
                        verbose_name="Servicio de Gas",
                    ),
                ),
                (
                    "land_area_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="land_properties",
                        to="properties.measurementunit",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_properties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
                "db_table": "properties",
            },
            bases=(properties.models.TitleCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LeadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del estado (ej: En Espera, Interesado, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Color en formato hex (ej: #007bff para azul)",
                        max_length=7,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de aparición en los filtros"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_statuses",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de Lead",
                "verbose_name_plural": "Estados de Lead",
                "db_table": "lead_statuses",
                "ordering": ["order", "name"],
                "unique_together": {("property", "name")},
            },
        ),
        migrations.CreateModel(
            name="PropertyChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=120)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_changes",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="properties/documents/")),
                ("title", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "description",
                    encrypted_model_fields.fields.EncryptedTextField(blank=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.documenttype",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.property",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "property_documents",
            },
            bases=(properties.models.TitleCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PropertyFinancialInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_commission_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "final_commission_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "negotiation_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_records",
                        to="properties.negotiationstatus",
                    ),
                ),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_info",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Información financiera de la propiedad",
                "verbose_name_plural": "Información financiera de propiedades",
                "db_table": "property_financial_info",
            },
        ),
        migrations.CreateModel(
            name="PropertyOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "last_name",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "maternal_last_name",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de documento",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                        null=True,
                        verbose_name="Género",
                    ),
                ),
                (
                    "phone",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "secondary_phone",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "email",
                    encrypted_model_fields.fields.EncryptedEmailField(
                        blank=True, null=True
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="owners/photos/"
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "address_exact",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dirección Exacta"
                    ),
                ),
                (
                    "address_coordinates",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Coordenadas",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.department",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.district",
                        verbose_name="Distrito",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.documenttype",
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.profession",
                    ),
                ),
            ],
            options={
                "db_table": "property_owners",
            },
            bases=(properties.models.TitleCaseMixin, models.Model),
        ),
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="properties.propertyowner",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.propertystatus",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_subtype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.propertysubtype",
            ),
        ),
        migrations.AddField(
            model_name="propertysubtype",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.propertytype",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.propertytype",
            ),
        ),
        migrations.CreateModel(
            name="PropertyWhatsAppLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_name",
                    models.CharField(
                        help_text="Nombre del enlace (ej: 'Facebook Ads - Villa Marina')",
                        max_length=100,
                    ),
                ),
                (
                    "unique_identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único para tracking",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("utm_source", models.CharField(blank=True, max_length=100, null=True)),
                ("utm_medium", models.CharField(default="whatsapp", max_length=100)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "utm_content",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_links_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_links",
                        to="properties.property",
                    ),
                ),
                (
                    "social_network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="whatsapp_links",
                        to="properties.socialnetwork",
                    ),
                ),
                (
                    "whatsapp_phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="whatsapp_links",
                        to="properties.whatsappphone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enlace WhatsApp de Propiedad",
                "verbose_name_plural": "Enlaces WhatsApp de Propiedades",
                "db_table": "property_whatsapp_links",
                "ordering": ["-created_at"],
                "unique_together": {("property", "social_network", "whatsapp_phone")},
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provinces",
                        to="properties.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincias",
                "ordering": ["name"],
                "unique_together": {("department", "name")},
            },
        ),
        migrations.AddField(
            model_name="propertyowner",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.province",
                verbose_name="Provincia",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="properties.province",
            ),
        ),
        migrations.CreateModel(
            name="PropertyRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "floor_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.floortype",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.leveltype",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="properties.property",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "property_rooms",
                "ordering": ["level", "order"],
            },
            bases=(properties.models.TitleCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="properties/images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.imagetype",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image_ambiente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.roomtype",
                        verbose_name="Ambiente de la imagen",
                    ),
                ),
            ],
            options={
                "db_table": "property_images",
                "ordering": ["order"],
            },
            bases=(properties.models.TitleCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("first_message_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="properties.leadstatus",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_leads",
                        to="properties.property",
                    ),
                ),
                (
                    "whatsapp_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="properties.propertywhatsapplink",
                    ),
                ),
                (
                    "social_network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="properties.socialnetwork",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead de WhatsApp",
                "verbose_name_plural": "Leads de WhatsApp",
                "db_table": "whatsapp_leads",
                "ordering": ["-created_at"],
                "unique_together": {("property", "phone_number")},
            },
        ),
        migrations.AddField(
            model_name="propertyowner",
            name="tags",
            field=models.ManyToManyField(blank=True, to="properties.tag"),
        ),
        migrations.AddField(
            model_name="property",
            name="tags",
            field=models.ManyToManyField(blank=True, to="properties.tag"),
        ),
        migrations.CreateModel(
            name="Urbanization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urbanizations",
                        to="properties.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Urbanización",
                "verbose_name_plural": "Urbanizaciones",
                "ordering": ["name"],
                "unique_together": {("district", "name")},
            },
        ),
        migrations.AddField(
            model_name="propertyowner",
            name="urbanization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.urbanization",
                verbose_name="Urbanización",
            ),
        ),
        migrations.CreateModel(
            name="PropertyVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="properties/videos/")),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="properties.property",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.videotype",
                    ),
                ),
            ],
            options={
                "db_table": "property_videos",
            },
            bases=(properties.models.TitleCaseMixin, models.Model),
        ),
        migrations.AddField(
            model_name="property",
            name="water_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="water_properties",
                to="properties.waterservicetype",
                verbose_name="Servicio de Agua",
            ),
        ),
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("incoming", "Entrante"), ("outgoing", "Saliente")],
                        max_length=10,
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("message_body", models.TextField()),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("media_url", models.URLField(blank=True, null=True)),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        help_text="image, video, document, audio",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="properties.lead",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_conversations",
                        to="properties.property",
                    ),
                ),
                (
                    "sent_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversación de WhatsApp",
                "verbose_name_plural": "Conversaciones de WhatsApp",
                "db_table": "whatsapp_conversations",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="district",
            unique_together={("province", "name")},
        ),
    ]
