# Generated by Django 5.2.8 on 2025-12-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyowner',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='propertyowner',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='propertyowner',
            name='identity_document',
        ),
    ]
