# Generated by Django 5.2.8 on 2025-12-11 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Número de WhatsApp (solo dígitos)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nombre o alias para mostrar", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Número WhatsApp",
                "verbose_name_plural": "Números WhatsApp",
                "db_table": "whatsapp_numbers",
                "ordering": ["display_name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="propertywhatsapplink",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="propertywhatsapplink",
            name="whatsapp_number",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="whatsapp_links",
                to="properties.whatsappnumber",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="propertywhatsapplink",
            unique_together={("property", "social_network", "whatsapp_number")},
        ),
        migrations.RemoveField(
            model_name="propertywhatsapplink",
            name="whatsapp_phone",
        ),
        migrations.DeleteModel(
            name="WhatsAppPhone",
        ),
    ]
