# Generated by Django 5.2.8 on 2025-12-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_remove_propertyowner_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyowner",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="propertyowner",
            name="document_number",
            field=models.CharField(
                default="", max_length=50, verbose_name="Número de documento"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="propertyowner",
            name="gender",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                default="",
                max_length=1,
                verbose_name="Género",
            ),
            preserve_default=False,
        ),
    ]
