# Generated by Django 5.2.8 on 2025-12-11 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_whatsappnumber_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UTMClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_id", models.CharField(db_index=True, max_length=50)),
                ("utm_source", models.CharField(blank=True, max_length=100, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "utm_content",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referer", models.TextField(blank=True, null=True)),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, help_text="IPv4/IPv6", max_length=45, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "whatsapp_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utm_clicks",
                        to="properties.propertywhatsapplink",
                        db_constraint=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "UTM Click",
                "verbose_name_plural": "UTM Clicks",
                "db_table": "utm_clicks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tracking_id"], name="utm_clicks_trackin_26fc89_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="utm_clicks_created_b51602_idx"
                    ),
                ],
            },
        ),
    ]
