# Generated by Django 5.2.8 on 2025-12-02 16:20

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_propertyowner_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyowner",
            name="document_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Número de documento"
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.documenttype",
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="email",
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="first_name",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                max_length=1,
                verbose_name="Género",
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="last_name",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="phone",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
