# Generated by Django 5.2.8 on 2025-12-11 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_utmclick"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utmclick",
            name="whatsapp_link",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="utm_clicks",
                to="properties.propertywhatsapplink",
            ),
        ),
    ]
