# Generated by Django 5.2.8 on 2025-12-02 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_alter_propertyowner_document_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="coordinates",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="property",
            name="exact_address",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Dirección Exacta (para mapa)"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="real_address",
            field=models.TextField(
                blank=True,
                help_text="Dirección exacta que aparece en documentos legales",
                verbose_name="Dirección Real (de documentos)",
            ),
        ),
        migrations.AlterField(
            model_name="propertydocument",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.documenttype",
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.imagetype",
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="address_coordinates",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Coordenadas"
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="address_exact",
            field=models.TextField(blank=True, verbose_name="Dirección Exacta"),
        ),
        migrations.AlterField(
            model_name="propertyvideo",
            name="video_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.videotype",
            ),
        ),
    ]
