# Generated by Django 5.2.8 on 2025-12-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_utmclick_whatsapp_link'),
    ]

    operations = [
        # Registrar los modelos en el estado de migraciones y usar SQL seguro para la base de datos
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'operation_types')\n"
                        "BEGIN\n"
                        "CREATE TABLE dbo.operation_types (\n"
                        "    id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,\n"
                        "    name NVARCHAR(100) NOT NULL UNIQUE,\n"
                        "    description NVARCHAR(MAX) NULL,\n"
                        "    code NVARCHAR(20) NOT NULL UNIQUE,\n"
                        "    [order] INT NOT NULL DEFAULT 0,\n"
                        "    is_active BIT NOT NULL DEFAULT 1,\n"
                        "    created_at DATETIME2 NOT NULL DEFAULT GETDATE()\n"
                        ");\n"
                        "END\n"
                        "ELSE\n"
                        "BEGIN\n"
                        "    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.operation_types') AND name = 'order')\n"
                        "    BEGIN\n"
                        "        ALTER TABLE dbo.operation_types ADD [order] INT NOT NULL DEFAULT 0;\n"
                        "    END\n"
                        "END"
                    ),
                    reverse_sql=(
                        "IF EXISTS (SELECT * FROM sys.tables WHERE name = 'operation_types')\n"
                        "BEGIN\n"
                        "    DROP TABLE dbo.operation_types;\n"
                        "END"
                    )
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='OperationType',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, unique=True)),
                        ('description', models.TextField(blank=True)),
                        ('code', models.CharField(max_length=20, unique=True)),
                        ('order', models.PositiveIntegerField(default=0)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'verbose_name': 'Tipo de Operación',
                        'verbose_name_plural': 'Tipos de Operación',
                        'db_table': 'operation_types',
                        'ordering': ['order', 'name'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'property_conditions')\n"
                        "BEGIN\n"
                        "CREATE TABLE dbo.property_conditions (\n"
                        "    id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,\n"
                        "    name NVARCHAR(100) NOT NULL UNIQUE,\n"
                        "    description NVARCHAR(MAX) NULL,\n"
                        "    [order] INT NOT NULL DEFAULT 0,\n"
                        "    is_active BIT NOT NULL DEFAULT 1,\n"
                        "    created_at DATETIME2 NOT NULL DEFAULT GETDATE()\n"
                        ");\n"
                        "END\n"
                        "ELSE\n"
                        "BEGIN\n"
                        "    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.property_conditions') AND name = 'order')\n"
                        "    BEGIN\n"
                        "        ALTER TABLE dbo.property_conditions ADD [order] INT NOT NULL DEFAULT 0;\n"
                        "    END\n"
                        "END"
                    ),
                    reverse_sql=(
                        "IF EXISTS (SELECT * FROM sys.tables WHERE name = 'property_conditions')\n"
                        "BEGIN\n"
                        "    DROP TABLE dbo.property_conditions;\n"
                        "END"
                    )
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='PropertyCondition',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, unique=True)),
                        ('description', models.TextField(blank=True)),
                        ('order', models.PositiveIntegerField(default=0)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'verbose_name': 'Condición de Propiedad',
                        'verbose_name_plural': 'Condiciones de Propiedad',
                        'db_table': 'property_conditions',
                        'ordering': ['order', 'name'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.properties') AND name = 'operation_type_id')\n"
                        "BEGIN\n"
                        "    ALTER TABLE dbo.properties ADD operation_type_id BIGINT NULL;\n"
                        "END\n"
                        "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'fk_properties_operation_type')\n"
                        "BEGIN\n"
                        "    ALTER TABLE dbo.properties WITH CHECK ADD CONSTRAINT fk_properties_operation_type FOREIGN KEY (operation_type_id) REFERENCES dbo.operation_types(id);\n"
                        "END"
                    ),
                    reverse_sql=(
                        "IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'fk_properties_operation_type')\n"
                        "BEGIN\n"
                        "    ALTER TABLE dbo.properties DROP CONSTRAINT fk_properties_operation_type;\n"
                        "END\n"
                        "IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.properties') AND name = 'operation_type_id')\n"
                        "BEGIN\n"
                        "    ALTER TABLE dbo.properties DROP COLUMN operation_type_id;\n"
                        "END"
                    )
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='property',
                    name='operation_type',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.operationtype', verbose_name='Tipo de Operación'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.properties') AND name = 'condition_id')\n"
                        "BEGIN\n"
                        "    ALTER TABLE dbo.properties ADD condition_id BIGINT NULL;\n"
                        "END\n"
                        "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'fk_properties_condition')\n"
                        "BEGIN\n"
                        "    ALTER TABLE dbo.properties WITH CHECK ADD CONSTRAINT fk_properties_condition FOREIGN KEY (condition_id) REFERENCES dbo.property_conditions(id);\n"
                        "END"
                    ),
                    reverse_sql=(
                        "IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'fk_properties_condition')\n"
                        "BEGIN\n"
                        "    ALTER TABLE dbo.properties DROP CONSTRAINT fk_properties_condition;\n"
                        "END\n"
                        "IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.properties') AND name = 'condition_id')\n"
                        "BEGIN\n"
                        "    ALTER TABLE dbo.properties DROP COLUMN condition_id;\n"
                        "END"
                    )
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='property',
                    name='condition',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertycondition', verbose_name='Condición Física'),
                ),
            ],
        ),
    ]
