# Generated by Django 5.2.8 on 2025-12-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_alter_property_coordinates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="built_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="built_area_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="built_properties",
                to="properties.measurementunit",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="land_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="land_area_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="land_properties",
                to="properties.measurementunit",
            ),
        ),
    ]
