# Generated by Django 5.2.8 on 2025-12-03 02:23

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0006_alter_property_built_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyowner",
            name="address_coordinates",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Coordenadas"
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="address_exact",
            field=models.TextField(
                blank=True, null=True, verbose_name="Dirección Exacta"
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="company",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.department",
                verbose_name="Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.district",
                verbose_name="Distrito",
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="document_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de documento"
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="email",
            field=encrypted_model_fields.fields.EncryptedEmailField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="first_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                max_length=1,
                null=True,
                verbose_name="Género",
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="last_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="maternal_last_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="observations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="phone",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.province",
                verbose_name="Provincia",
            ),
        ),
        migrations.AlterField(
            model_name="propertyowner",
            name="secondary_phone",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]
