# Generated by Django 5.2.8 on 2025-12-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_seed_paymentmethods'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_blob',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
