# Generated by Django 5.2.8 on 2025-12-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_seed_paymentmethods'),
    ]

    operations = [
        # Intentionally left blank to avoid destructive table renames that cause
        # duplicate object errors in environments where tables already exist.
    ]
