# Generated by Django 5.2.8 on 2025-12-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0008_propertychange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="amenities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="zoning",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
