# Generated by Django 5.2.8 on 2025-12-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertyimage_image_blob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
