# Generated by Django 5.2.8 on 2025-12-05 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0009_alter_property_amenities_alter_property_zoning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.propertystatus",
            ),
        ),
    ]
