# Generated by Django 5.2.8 on 2025-12-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='unit_location',
            field=models.CharField(blank=True, choices=[('basement', 'Sótano'), ('1', '1er piso'), ('2', '2do piso'), ('3', '3er piso'), ('4', '4to piso'), ('5', '5to piso'), ('6', '6to piso'), ('7', '7mo piso'), ('8', '8vo piso'), ('9', '9no piso'), ('10', '10mo piso')], max_length=20, null=True, verbose_name='Ubicación (nivel)'),
        ),
    ]
