# Generated by Django 5.2.8 on 2025-12-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_alter_property_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
