# Generated by Django 5.2.8 on 2025-12-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_unit_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='parking_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo adicional por estacionamiento si no está incluido en el precio', max_digits=10, null=True, verbose_name='Costo Estacionamiento'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_cost_included',
            field=models.BooleanField(default=False, verbose_name='Estacionamiento incluido en precio'),
        ),
    ]
