# Generated by Django 5.2.8 on 2025-12-05 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0011_alter_property_department_alter_property_district_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertychange",
            old_name="field",
            new_name="field_name",
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="code",
            field=models.CharField(blank=True, default="", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="coordinates",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.currency",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="property",
            name="exact_address",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Dirección Exacta (para mapa)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="floors",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="garage_spaces",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="half_bathrooms",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="properties.propertyowner",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_subtype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.propertysubtype",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.propertytype",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="real_address",
            field=models.TextField(
                blank=True,
                help_text="Dirección exacta que aparece en documentos legales",
                null=True,
                verbose_name="Dirección Real (de documentos)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="urbanization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertyvideo",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
