# Generated by Django 5.2.8 on 2025-12-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_parking_cost_property_parking_cost_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_project',
            field=models.BooleanField(default=False, verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='property',
            name='project_name',
            field=models.CharField(blank=True, help_text='Nombre para agrupar propiedades cuando se trate de un proyecto', max_length=200, null=True, verbose_name='Nombre de proyecto'),
        ),
    ]
