# Generated by Django 5.2.8 on 2026-01-03 18:52

import django.db.models.deletion
import encrypted_model_fields.fields
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_is_project_property_project_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('phone', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('budget_type', models.CharField(choices=[('approx', 'Aproximado'), ('range', 'Rango')], default='approx', max_length=20)),
                ('budget_approx', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('half_bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('garage_spaces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.district')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements_modified', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.paymentmethod')),
                ('property_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.propertysubtype')),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.propertytype')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.province')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertystatus')),
                ('urbanization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.urbanization')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'db_table': 'requirements',
                'ordering': ['-created_at'],
            },
            bases=(properties.models.TitleCaseMixin, models.Model),
        ),
    ]
