# Generated by Django 5.2.8 on 2026-01-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.currency'),
        ),
    ]
