# Generated by Django 5.2.8 on 2026-01-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_requirement_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='area_type',
            field=models.CharField(choices=[('approx', 'Aproximado'), ('range', 'Rango')], default='approx', max_length=20),
        ),
        migrations.AddField(
            model_name='requirement',
            name='land_area_approx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='land_area_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='land_area_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
