# Generated by Django 5.2.8 on 2026-01-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_requirement_area_type_requirement_land_area_approx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='requirements_multiple', to='properties.district'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='urbanizations',
            field=models.ManyToManyField(blank=True, related_name='requirements_multiple', to='properties.urbanization'),
        ),
    ]
