# Generated by Django 5.2.8 on 2026-01-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_requirement_districts_requirement_urbanizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='urbanization',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='urbanizations',
        ),
    ]
