# Generated by Django 5.2.8 on 2026-01-06 19:07

import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_remove_requirement_urbanization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#047D7D', help_text='Color en formato hex (ej: #047D7D)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
                'db_table': 'event_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fecha_evento', models.DateField(verbose_name='Fecha del evento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de término')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle de la visita')),
                ('interesado', models.CharField(blank=True, max_length=200, verbose_name='Interesado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='properties.property', verbose_name='Inmueble')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.eventtype', verbose_name='Tipo de evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'events',
                'ordering': ['-fecha_evento', '-hora_inicio'],
            },
            bases=(properties.models.TitleCaseMixin, models.Model),
        ),
    ]
