# Generated by Django 5.2.8 on 2026-01-06 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_eventtype_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='properties.propertyowner'),
        ),
    ]
