# Generated by Django 5.2.8 on 2026-01-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_requirement_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='properties.propertyowner', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='event',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_events', to='properties.property', verbose_name='Inmueble'),
        ),
    ]
