# Generated by Django 5.2.8 on 2026-01-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_event_contact_alter_event_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'floor_options',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='preferred_floors',
            field=models.ManyToManyField(blank=True, related_name='requirements', to='properties.flooroption'),
        ),
    ]
