# Generated by Django 5.2.8 on 2026-01-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_requirement_zonificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='frontera_approx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='frontera_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='frontera_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='frontera_type',
            field=models.CharField(choices=[('approx', 'Aproximada'), ('range', 'Rango')], default='approx', max_length=20),
        ),
        migrations.AlterField(
            model_name='zoningoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
