# Generated by Django 5.2.8 on 2026-01-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_requirement_frontera_approx_requirement_frontera_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ascensor',
            field=models.CharField(choices=[('yes', 'Sí'), ('no', 'No')], max_length=3, null=True, blank=True, verbose_name='Ascensor'),
        ),
    ]
