# Generated by Django 5.2.8 on 2026-01-08 12:07

from django.db import migrations, models


def create_contract_types(apps, schema_editor):
    ContractType = apps.get_model('properties', 'ContractType')
    entries = [
        {'name': 'Exclusivo', 'code': 'exclusivo'},
        {'name': 'Semi exclusivo', 'code': 'semi_exclusivo'},
        {'name': 'No exclusivo', 'code': 'no_exclusivo'},
    ]
    for e in entries:
        ContractType.objects.create(name=e['name'], code=e['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_property_ascensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contract_types',
                'ordering': ['name'],
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
            },
        ),
        migrations.AddField(
            model_name='propertyfinancialinfo',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.PROTECT, related_name='financial_records', to='properties.contracttype', verbose_name='Tipo de Contrato'),
        ),
        migrations.RunPython(create_contract_types),
    ]
