# Generated by Django 5.2.8 on 2026-01-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_propertyfinancial_contracttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='sensible',
            field=models.BooleanField(default=False, verbose_name='Sensible'),
        ),
    ]
