# Generated by Django 5.2.8 on 2026-01-08 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_propertyimage_sensible'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identificador del criterio, ej: property_type, district, price', max_length=100, unique=True)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Peso de Matching',
                'verbose_name_plural': 'Pesos de Matching',
                'db_table': 'matching_weights',
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Datos opcionales sobre el evento', null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='properties.property')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='properties.requirement')),
            ],
            options={
                'db_table': 'match_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
