# Generated by Django 5.2.8 on 2026-01-20 20:07

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_matchingweight_matchevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=255, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('ruc', models.CharField(max_length=11, verbose_name='RUC')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('distrito', models.CharField(max_length=100, verbose_name='Distrito')),
                ('urbanizacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Urbanización')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency/logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Datos de la Inmobiliaria',
                'verbose_name_plural': 'Datos de la Inmobiliaria',
                'db_table': 'agency_config',
            },
            bases=(properties.models.TitleCaseMixin, models.Model),
        ),
    ]
