# Generated by Django 5.2.10 on 2026-01-30 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_agencyconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_matches', to='properties.property')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='properties.requirement')),
            ],
            options={
                'db_table': 'requirement_matches',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['requirement', '-score'], name='requirement_require_654413_idx'), models.Index(fields=['property', '-score'], name='requirement_propert_f4b28d_idx')],
                'unique_together': {('requirement', 'property')},
            },
        ),
    ]
