# Generated by Django 5.2.10 on 2026-02-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_requirementmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
