# Generated by Django 5.2.10 on 2026-02-06 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_documenttype_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['property', 'document_type'], name='idx_propdoc_prop_doctype'),
        ),
        migrations.AddConstraint(
            model_name='propertydocument',
            constraint=models.UniqueConstraint(fields=('property', 'document_type'), name='uq_property_documents_property_document_type'),
        ),
    ]
