# Generated by Django 5.2.10 on 2026-02-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_propertydocument_idx_propdoc_prop_doctype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservada'), ('sold', 'Vendida'), ('unavailable', 'No disponible'), ('paused', 'Pausada')], db_index=True, default='available', max_length=20, verbose_name='Estado comercial'),
        ),
    ]
