# Generated by Django 5.2.10 on 2026-02-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_backfill_event_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='wp_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='wp_post_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='wp_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
