# Generated by Django 5.2.10 on 2026-02-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_property_wp_last_sync_property_wp_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='wp_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='wp_media_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='wp_source_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
