# Generated by Django 5.2.10 on 2026-02-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_propertyimage_wp_last_sync_propertyimage_wp_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservada'), ('sold', 'Vendida'), ('unavailable', 'No disponible'), ('paused', 'Pausada'), ('catchment', 'En proceso de captacion')], db_index=True, default='available', max_length=20, verbose_name='Estado comercial'),
        ),
    ]
