# Generated by Django 5.2.10 on 2026-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_propertydocument_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='properties/documents/'),
        ),
    ]
