# Generated by Django 5.2.10 on 2026-02-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0041_alter_propertydocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seguimiento',
            field=models.TextField(blank=True, verbose_name='Seguimiento de la visita'),
        ),
    ]
