# Generated by Django 5.2.10 on 2026-02-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_event_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
