# Generated by Django 5.2.10 on 2026-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0043_property_source_property_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='source_published_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
