# Generated by Django 5.2.10 on 2026-02-28 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_property_source_published_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='area_type',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='ascensor',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='budget_approx',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='budget_type',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='department',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='district',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='frontera_approx',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='frontera_max',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='frontera_min',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='frontera_type',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='garage_spaces',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='half_bathrooms',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='land_area_approx',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='number_of_floors',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='preferred_floors',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='province',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='zonificaciones',
        ),
        migrations.AddField(
            model_name='requirement',
            name='antiquity_years_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='antiquity_years_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirement',
            name='bathrooms_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='bathrooms_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='bedrooms_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='bedrooms_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='built_area_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='built_area_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='floors_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='floors_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='garage_spaces_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='garage_spaces_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='has_elevator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='operation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.operationtype'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='pet_friendly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='requirements', to='properties.district'),
        ),
    ]
