# Generated by Django 5.2.10 on 2026-02-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0045_alter_requirement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
