# Generated by Django 5.2.10 on 2026-02-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0046_requirement_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='notes_message_ws',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='property_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='properties.propertystatus'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_group',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
