# Generated by Django 5.2.10 on 2026-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0047_requirement_notes_message_ws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='import_batch',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
