# Generated by Django 5.2.10 on 2026-02-28 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0048_requirement_import_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='import_row_sig',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('import_batch', 'import_row_sig'), name='uq_requirement_import_row'),
        ),
    ]
