# Generated by Django 5.2.10 on 2026-03-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0049_requirement_import_row_sig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='district_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.district'),
        ),
        migrations.AddField(
            model_name='property',
            name='urbanization_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.urbanization'),
        ),
    ]
