# Generated by Django 5.2.10 on 2026-03-03 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0050_property_district_fk_property_urbanization_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['district_fk'], name='idx_prop_district_fk'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['district_fk', 'operation_type', 'property_type', 'currency', 'availability_status'], name='idx_prop_match_core'),
        ),
    ]
