# Generated by Django 5.2.10 on 2026-03-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0051_property_idx_prop_district_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
