# Generated by Django 5.2.10 on 2026-03-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0053_migrate_ascensor_to_has_elevator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
