# Generated by Django 5.2.10 on 2026-03-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0054_alter_property_has_elevator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappconversation',
            name='lead',
        ),
        migrations.AlterUniqueTogether(
            name='leadstatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='property',
        ),
        migrations.RemoveField(
            model_name='whatsappconversation',
            name='property',
        ),
        migrations.RemoveField(
            model_name='whatsappconversation',
            name='sent_by_user',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='LeadStatus',
        ),
        migrations.DeleteModel(
            name='WhatsAppConversation',
        ),
    ]
