# Generated by Django 5.2.10 on 2026-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0056_canallead_leadstatus_lead_event_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='username',
            field=models.CharField(db_index=True, default='temp_username', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
