# Generated by Django 5.2.10 on 2026-03-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0057_lead_username_alter_lead_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
