# Generated by Django 5.2.10 on 2026-03-06 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0058_alter_lead_date_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='sent', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='properties.currency')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='properties.lead')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='properties.paymentmethod')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='properties.property')),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals_requested', to=settings.AUTH_USER_MODEL)),
                ('requirement_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='properties.requirementmatch')),
                ('responded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_responded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
