# Generated by Django 5.2.10 on 2026-03-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0059_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('sent', 'Enviada'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], db_index=True, default='sent', max_length=20),
        ),
    ]
