# Generated by Django 5.2.10 on 2026-03-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0061_proposal_response_message_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='properties.proposal', verbose_name='Propuesta'),
        ),
    ]
