# Generated by Django 5.2.10 on 2026-03-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0062_event_proposal'),
        ('users', '0005_area_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='visible_for_roles',
            field=models.ManyToManyField(blank=True, related_name='visible_properties', to='users.role', verbose_name='Visible para roles'),
        ),
    ]
