# Generated by Django 5.2.10 on 2026-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0063_property_visible_for_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado de confirmación'),
        ),
    ]
