# Generated by Django 5.2.10 on 2026-03-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0064_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de rechazo'),
        ),
    ]
