# Generated by Django 5.2.8 on 2025-12-01 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(blank=True, max_length=150)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('blocked', 'Bloqueado')], default='pending', max_length=20)),
                ('is_trusted', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo autorizado',
                'verbose_name_plural': 'Dispositivos autorizados',
                'db_table': 'security_authorizeddevice',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['device_id'], name='security_au_device__2e547e_idx'), models.Index(fields=['user', 'status'], name='security_au_user_id_54b671_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='security_device_user_device_unique')],
            },
        ),
    ]
