# Generated by Django 5.2.8 on 2026-01-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_unauthorizeddeviceloginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_verification_enabled', models.BooleanField(default=True, help_text='Si se desactiva, los usuarios podrán iniciar sesión desde cualquier dispositivo sin aprobación previa.', verbose_name='Verificación de dispositivos activa')),
            ],
            options={
                'verbose_name': 'Configuración de Seguridad',
                'verbose_name_plural': 'Configuraciones de Seguridad',
            },
        ),
    ]
